name: GitHub Actions test
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.5
        target: esp32p4
        command: idf.py -D SDKCONFIG_DEFAULTS="sdkconfig.defaults" build all size-components size
